language: node_js
node_js:
  - "5.1"
python:
  - "3.5"
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
before_install:
  - echo "before install"
  - wget https://bootstrap.pypa.io/get-pip.py ~/get-pip.py
  - sudo python3.5 ~/get-pip.py
  - sudo pip3.5 install setuptools --upgrade
script: >
  pushd monitor-api &&
  sudo python3.5 get-pip.py &&
  sudo pip3.5 install -r ./requirements.txt &&
  PYTHONPATH="${PYTHONPATH}:$(pwd)" py.test &&
  popd
  pushd monitor-ui &&
  npm install &&
  npm test &&
  popd

