language: python
python:
  - "3.5"
node_js:
  - "5.1"
before_install:
  - sudo apt-get install nodejs
  - sudo apt-get install npm
install: "pip install -r ./monitor-api/requirements.txt"
script: >
  cd ../monitor-api &&
  sudo pip install -r ./requirements.txt &&
  PYTHONPATH="${PYTHONPATH}:$(pwd)" py.test

