language: node_js
node_js:
  - "5.1"
python:
  - "3.5"
before_install:
  - sudo apt-get install python3
  - sudo apt-get install python3-setuptools
  - sudo apt-get install python3-pip
script: cd monitor-ui && npm install && npm test && cd ../monitor-api && echo $(pip --version) && sudo pip3 install -r ./requirements.txt && PYTHONPATH=${PYTHONPATH}:./ py.test

