language: node_js
node_js:
  - "5.1"
python:
  - "3.5"
before_install:
  - sudo apt-get install python3
  - sudo apt-get install python3-setuptools
  - sudo easy_install3 pip
script: >
  cd monitor-ui &&
  npm install &&
  npm test &&
  cd ../monitor-api &&
  sudo pip3 install -r ./requirements.txt &&
  PYTHONPATH="${PYTHONPATH}:$(pwd)" py.test

