language: python
python:
  - "3.5"
before_install:
  - sudo apt-get install -y nodejs
  - sudo apt-get install -y npm
install: "pip install -r ./monitor-api/requirements.txt"
script: >
  pushd monitor-api &&
  sudo pip install -r ./requirements.txt &&
  PYTHONPATH="${PYTHONPATH}:$(pwd)" py.test &&
  popd

