sudo: required
language: node_js
dist: trusty
node_js:
  - "5.1"
python:
  - "3.5"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
    packages:
      - python3.5
      - g++-4.8
      - openjdk-7-jdk
script:
  - pushd monitor-api
  - sudo wget https://bootstrap.pypa.io/get-pip.py
  - sudo python3.5 get-pip.py
  - sudo pip3.5 install -r ./requirements.txt
  - PYTHONPATH="${PYTHONPATH}:$(pwd)" py.test
  - popd 
  - pushd monitor-ui
  - npm install
  - npm test
  - popd

