language: python
python:
  - "3.5"
node_js:
  - "5.1"
before_install:
  - curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
  - sudo apt-get install nodejs
  - sudo apt-get install npm
install: "pip install -r ./monitor-api/requirements.txt"
script: >
  pushd monitor-api &&
  sudo pip install -r ./requirements.txt &&
  PYTHONPATH="${PYTHONPATH}:$(pwd)" py.test &&
  popd

