language: node_js
node_js:
  - "5.1"
before_install:
  - sudo apt-get install python3
  - sudo apt-get install python3-setuptools
script: cd monitor-ui && npm install && npm test && cd ../monitor-api && sudo pip install -r ./requirements.txt && PYTHONPATH=${PYTHONPATH}:./ py.test

