language: node_js
node_js:
  - "5.1"
python:
  - "3.5"
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
before_install:
  - sudo install python3.5
  - echo $(dpkg -L python3.5)
install: "pip install -r ./monitor-api/requirements.txt"
script: >
  pushd monitor-api &&
  sudo pip3 install -r ./requirements.txt &&
  PYTHONPATH="${PYTHONPATH}:$(pwd)" py.test &&
  popd
  pushd monitor-ui &&
  npm install &&
  npm test &&
  popd

