LOGGER_NAME = app
staticFolder = "./static-dev"
staticUrl = "/static"
templateFolder = "templates"

SQLALCHEMY_DATABASE_URI = "sqlite:///./dev.sqlite"
# SQLALCHEMY_BINDS =
# SQLALCHEMY_NATIVE_UNICODE =
SQLALCHEMY_ECHO = true
# SQLALCHEMY_RECORD_QUERIES =
# SQLALCHEMY_POOL_SIZE =
# SQLALCHEMY_POOL_TIMEOUT =
# SQLALCHEMY_POOL_RECYCLE =
# SQLALCHEMY_MAX_OVERFLOW =
SQLALCHEMY_COMMIT_ON_TEARDOWN = false
# SQLALCHEMY_TRACK_MODIFICATIONS =

[jwt]
pub = "../castore/bpmon.pub"
prv = "../castore/bpmon.prv"
alg = "RS256"
leeway = 10
exp = 300
nbf = 0
header = "X-Access-Token"
verify_claims = ["signature", "exp", "nbf"]
required_claims = ["exp", "nbf"]


[log]
version = 1
incremental = false
disable_existing_loggers = true

[log.root]
level = "DEBUG"
handlers = ["console"]

[log.loggers]

[log.loggers.app]
level = "DEBUG"
handlers = ["console"]

[log.handlers]

[log.handlers.null]
level = "DEBUG"
class = "logging.NullHandler"

[log.handlers.console]
level = "DEBUG"
class = "logging.StreamHandler"
formatter = "default"

[log.formatters]

[log.formatters.default]
# format = "[%(levelname)s]P:%(process)d T:%(thread)d %(asctime)s %(name)s.%(funcName)s: %(message)s"
datefmt = "%Y-%b-%d %H:%M:%S"
