LOGGER_NAME = app
staticFolder = "./static-dev"
staticUrl = "/static"
templateFolder = "templates"

SQLALCHEMY_DATABASE_URI = "sqlite:///./dev.sqlite"
SQLALCHEMY_BINDS = null
SQLALCHEMY_NATIVE_UNICODE = null
SQLALCHEMY_ECHO = false
SQLALCHEMY_RECORD_QUERIES = null
SQLALCHEMY_POOL_SIZE = null
SQLALCHEMY_POOL_TIMEOUT = null
SQLALCHEMY_POOL_RECYCLE = null
SQLALCHEMY_MAX_OVERFLOW = null
SQLALCHEMY_COMMIT_ON_TEARDOWN = false
SQLALCHEMY_TRACK_MODIFICATIONS = null

[jwt]
pub = "../castore/bpmon.pub"
prv = "../castore/bpmon.prv"
realm = "Login Required"
alg = "RS256"
leeway = 10
prefix = "JWT"
exp = 300
nbf = 0
verify_claims = ["signature", "exp", "nbf", "iat"]
required_claims = ["exp", "iat", "nbf"]

[log]
version = 1
incremental = false
disable_existing_loggers = true

[log.root]
level = "DEBUG"
handlers = ["console"]

[log.loggers]

[log.loggers.app]
level = "DEBUG"
handlers = ["console"]

[log.handlers]

[log.handlers.null]
level = "DEBUG"
class = "logging.NullHandler"

[log.handlers.console]
level = "DEBUG"
class = "logging.StreamHandler"
formatter = "default"

[log.formatters]

[log.formatters.default]
# format = "[%(levelname)s]P:%(process)d T:%(thread)d %(asctime)s %(name)s.%(funcName)s: %(message)s"
datefmt = "%Y-%b-%d %H:%M:%S"
